# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoodNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoodNotes

pod 'BetterSegmentedControl', '~> 2.0'

  target 'MoodNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoodNotesUITests' do
    # Pods for testing
  end

end
